[package]
name = "local-encoding"
license = "MIT"
version = "0.1.0"
authors = [ "Artem V. Navrotskiy <bozaro@buzzsoft.ru>" ]
description = "Rust library for encoding/decoding string with local charset. It usefull for work with ANSI strings on Windows."
repository = "https://github.com/bozaro/local-encoding-rs"

[dependencies]
